image: gradle:4.7-jdk8-alpine

stages:
  - build
  - test
  - deploy

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

Build:
  stage: build
  script:
    - gradle clean build --refresh-dependencies

Test:
  stage: test
  script:
    - gradle check
    - gradle jacocoTestReport
    - gradle jacocoTestCoverageVerification

DeployProduction:
  image: ruby:2.4
  stage: deploy
  before_script:
    - gem install dpl
    - wget -qO- https://cli-assets.heroku.com/install-ubuntu.sh | sh
  script:
    - dpl --provider=heroku --app=laksamana-line-bot --api-key=237ac245-bf30-410b-8161-23a9693b87fb
  when: manual
  environment:
    name: production
    url: https://laksamana-line-bot.herokuapp.com/
